### ISSUE TITLE
Set SMB client name to "machine1" in the IMMS

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-industrial-pilot#153]
The IDS matches the SMB client names to detect bad clients.

To get this working, we need to set the name of the SMB client (the one running in the IMMS/DT container) to be `machine1` (that is the default we agreed for now).

We need to investigate how this can be done. Need to google a bit.

**Comment by stefanbschneider** [comment]
Seems like you can just specify a username with `-U` when using the samba client: https://www.samba.org/samba/docs/current/man-html/smbclient.1.html

But I don't see any Samba-specific code in the [`IMMS_APP.py`](https://github.com/sonata-nfv/tng-industrial-pilot/blob/master/vnfs/dt-digitaltwin-docker/containers/IMMS_APP/IMMS_APP.py). It just looks like regular file reading and writing. Is the Samba connection handled somewhere else?

**Comment by mpeuster** [comment]
Yes. Samba is mounted in the start script. Username is not what we need. Maybe it simply uses the host name of the machine the SMB client runs on.
