### ISSUE TITLE
Detailed definition of VNF features where missing

### ISSUE THREAD

**Issue by danielbehnke** [sonata-nfv/tng-industrial-pilot#20]
please ask if information is needed, might be topic for next telco

**Comment by jbonnet** [comment]
@danielbehnke I'd probably open issues per VNF, maybe using tags to distinguish them? E.g., issue 'Data exchange format' would be tagged both for VNF 'Analytics' (or wahetever the name) and 'Data collector'. Something like that...

**Comment by danielbehnke** [comment]
Issue for each VNF created.
