### ISSUE TITLE
VNF Cloud Connector (CC)

### ISSUE THREAD

**Issue by danielbehnke** [sonata-nfv/tng-industrial-pilot#22]

**Comment by mpeuster** [comment]
I will take care of this one.

Will start to work on it starting from 26th November.

Will have a MQTT broker, a database and some processing functionality to relay the data to the cloud backend (Azure).

**Comment by mpeuster** [comment]
Moved to dedicated project: https://github.com/sonata-nfv/tng-industrial-pilot/projects/1
