### ISSUE TITLE
VNF Edge Analytics Engine

### ISSUE THREAD

**Issue by danielbehnke** [sonata-nfv/tng-industrial-pilot#23]
Analyze machine data on a random basis, based on result execute immediate actions.

Leverage Grafana to build dashboards with nice graphs and alerts for the EAE: https://github.com/sonata-nfv/tng-industrial-pilot/issues/43#issuecomment-443738517

- [x] Build on existing Grafana docker image
- [x] K8s: Configure to connect to the CC's Prometheus CDU
- [x] K8s:Configure dashboard to show some useful graphs
- [x] K8s:Configure some example alerts with email notifications
- [x] vim-emu: Configure to connect to the CC's Prometheus CDU
- [x] vim-emu: dashboard to show some useful graphs
- [x] vim-emu: some example alerts with email notifications

Note: If we have many NS1 (vim-emu case) you will be always logged out if you switch from one Grafana browser window to another. Not a big deal, but don't be surprised.

**Comment by StefanUPB** [comment]
Todos:

* [ ] MQTT client that subscribes to updates from the MDC via the CC
* [ ] REST interface that allows to
  * [ ] Set/get/update/delete thresholds for specific metrics (e.g., temperature)
  * [ ] Returns the metric values over time
  * [ ] Returns whether the current metric values are ok (e.g., green, yellow, red)
* [ ] Simple frontend that shows some plots, eg, values over time + thresholds and traffic lights
* [ ] Deploy in Docker container

**Comment by StefanUPB** [comment]
Actually, leverage CC's Prometheus DB, rather than subscribing to MQTT for now.

**Comment by StefanUPB** [comment]
Note to self: When using Docker on windows, connect to the IP of the docker machine (eg, 192.168.99.100) not localhost.

**Comment by stefanbschneider** [comment]
For running on `vim-emu`, I need to extend the base container and use `VIM_EMU_CMD` and `CMD` as in [this example](https://github.com/mpeuster/son-examples/blob/master/vnfs/sonata-snort-ids-vnf-docker/Dockerfile) such that the container runs bash and doesn't block, which is necessary for `vim-emu` to configure the containers.

If the base container is based on some strange Linux, it might not work (since `iptables` works differently), and I'd have to use the `ubuntu` base image and install Grafana on there.

**Comment by stefanbschneider** [comment]
When deploying the container on the VM (`linux-dev`), the Grafana GUI is available at `linux-dev.cs.upb.de:3000` --> works.

Following the walkthrough here, the container can be deployed on the emulator and is shown as running with `vim-emu compute list`. But how can I access the GUI from the container running within the emulator?

**Comment by stefanbschneider** [comment]
Manual deployment of pilot (incl Prometheus) works now (see #72 ). There it's also possible to manually configure Grafana through the GUI to connect to Prometheus and show data from the DT.

Prometheus URL: `http://ns1-cc-service:9090` (the k8s service name of the CC)
Metric: `wimms_em63_actsimpara2`

Next, this should be preconfigured or configurable through env vars and directly show some nice plots on startup. To avoid manual setup.

**Comment by stefanbschneider** [comment]
Provisioning a pre-configured data source works now to connect to the CC's Prometheus DB. But have to specify the IP/URL in the corresponding `datasource.yml`. This should happen automatically based on the env var set by the SP, which points to the CC.

**Comment by stefanbschneider** [comment]
Python script is implemented but still needs to be tested and integrated into the Dockerfile.

Maybe even better idea than overriding the `ENTRYPOINT` in the [Grafana Dockerfile](https://github.com/grafana/grafana-docker/blob/master/Dockerfile#L38): Simply rename Grafana's `run.sh` into something else ( `run_grafana.sh`) and copy own `run,sh`, which calls first my script and then the `grafana_run.sh`. This will then be called by the existing Grafana entry point without having to override anything.

**Comment by stefanbschneider** [comment]
Started working on script and updating Dockerfile, but still needs to be tested and debugged.

**Comment by stefanbschneider** [comment]
See Readme for current status: https://github.com/sonata-nfv/tng-industrial-pilot/blob/eae/vnfs/eae-edgeanalyticsengine-docker/containers/README.md

**Comment by stefanbschneider** [comment]
Current work is in `eae` branch: https://github.com/sonata-nfv/tng-industrial-pilot/tree/eae/vnfs/eae-edgeanalyticsengine-docker/containers

**Comment by stefanbschneider** [comment]
Pointer to Grafana docs: https://grafana.com/docs/administration/provisioning/

What we need is called "Provisioning"

**Comment by stefanbschneider** [comment]
When deploying on the emulator, we use slightly different artifacts than for deployment on Kubernetes later on:

* [SDK projects](https://github.com/sonata-nfv/tng-industrial-pilot/tree/eae/sdk-projects): The ones for the emulator are suffixed with `-emulator` the ones for Kubernetes with `-k8s`.
  * We only use `tng-smpilot-ns1` and `-ns2`
  * There are a lot of other projects that are not relevant at all
  * Even ns1 and ns2 are probably fine and don't need adjustment for this issue
* [VNF implementation](https://github.com/sonata-nfv/tng-industrial-pilot/tree/eae/vnfs/eae-edgeanalyticsengine-docker/containers): Contains all files for building and running the Docker container
  * We use different Dockerfiles to build different version of the container image for the emulator and Kubernetes
  * `Dockerfile` is for Kubernetes, `Dockerfile.vimemu` for the emulator
  * The Docker images are tagged with `:k8s` for Kubernetes and `:vimemu` for the emulator
  * Most parts of the Dockerfile can be exactly the same for Kubernetes and emulator. We only need the last few lines [here](https://github.com/sonata-nfv/tng-industrial-pilot/blob/eae/vnfs/eae-edgeanalyticsengine-docker/containers/Dockerfile.vimemu#L38) to always be present in the emulator but not in Kubernetes. Best ask Manuel for explanation :)
  * Other files like `dashboard.json` etc are shared and used by both versions

**Comment by mpeuster** [comment]
I noticed another issue we have on the emulator. The used Grafana container seems not to be based on a default Ubuntu (trusty or xenial) image but on some lightweight other image.

Problem with this is that the container misses a lot of networking tools, e.g., ip etc. which means it can NOT run properly within the container.

See: https://github.com/containernet/containernet/wiki/Container-Requirements-and-Compatibility

**Comment by mpeuster** [comment]
vim-emu issues above resolved. Works well with vim-emu now.

**Comment by stefanbschneider** [comment]
@KaiHannemann The EAE looks nice and works well now, but there are three more tasks to finalize the EAE:

- [ ] Fix the automatic interconnection with the CC's Prometheus DB:

We need to update the [environmental variables that are currently used](https://github.com/sonata-nfv/tng-industrial-pilot/blob/master/vnfs/eae-edgeanalyticsengine-docker/containers/Dockerfile#L57) to get the IP address (and port) of the CC Prometheus DB. The Tango SP portal uses different env var names as you can see [here](https://github.com/sonata-nfv/tng-industrial-pilot/issues/76#issuecomment-502733390):

```
EU_5GTANGO_SMPILOT_CC_0_1_D8E33112_SERVICE_HOST=10.100.137.145
EU_5GTANGO_SMPILOT_CC_0_1_D8E33112_PORT_9090_TCP_PORT=9090
```

Since the `D8E33112` part is dynamic, you need to find the env var based on its prefix `EU_5GTANGO_SMPILOT_CC_0_1` and suffix `SERVICE_HOST` (best use Python's `string.split()` function).

@mpeuster Not sure if this also affects the emulator deployment somehow? Is the env var used there?

- [ ] Set the Grafana default dashboard, which you see after login, to show the smart manufacturing dashboard: https://stackoverflow.com/a/48212294

- [ ] Set up some example alerts and email notification, e.g., when the number of pieces reaches a certain number.

**Comment by mpeuster** [comment]
Yes, it will affect the emulator version. There the variable is used as well: https://github.com/sonata-nfv/tng-industrial-pilot/blob/master/vnfs/eae-edgeanalyticsengine-docker/containers/Dockerfile.vimemu#L64

So the reconfiguration script should be smart enough to also check those to variables first, and only search for the others, if these two are not found:

```
ENV eu.5gtango_smpilot-cc_0.1_prometheus_ip 30.0.0.4
ENV eu.5gtango_smpilot-cc_0.1_prometheus_port 9090
```

**Comment by stefanbschneider** [comment]
Closed by #156

**Comment by stefanbschneider** [comment]
@KaiHannemann apparently, this is the environmental variable you need to use `smpilot_cc_eu_5gtango_0_1_prometheus_ip=10.200.16.40`. So you can simply hard code it. Sorry for the confusion.

Currently, the environmental variable is not set directly after start. @felipevicens is working on it.

**Comment by stefanbschneider** [comment]
@KaiHannemann I just tested the deployment of NS1 (and NS2) with the latest version of the EAE (PR #162 ) and I can't access the Grafana web interface at all. When trying to access <public-eae-ip>:3000, the request just times out.

Can you please check and fix this? Seems like the Grafana service isn't started.

**Comment by KaiHannemann** [comment]
That's weird I checked it locally and it worked just fine. Will look into it when getting back home.

**Comment by stefanbschneider** [comment]
Nice, after the PR #173 I tested it again successfully now. Automatic connection to CC seems to work now! 👍
