### ISSUE TITLE
UseCase #2: Isolate a machine

### ISSUE THREAD

**Issue by danielbehnke** [sonata-nfv/tng-industrial-pilot#31]
Control instance for the management of network services and VNFs based on machine topology defined in the portal.

**Comment by mpeuster** [comment]
The realisation of this UC mainly depends on the developments of the FSM/SSM which I will document and capture in [this](https://github.com/sonata-nfv/tng-industrial-pilot/wiki/FSM-SSM-Development) wiki page.
